package com.dzpay.admin.model.skypg;

import java.util.Date;

public class TblapplyRegist {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_REG_DT
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpRegDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CONT_ID
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private Short contId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_NAME
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_SANG_HO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpSangHo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_TAX_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpTaxNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_NAME
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpOwnName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpOwnNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_ZIPCODE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpZipcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_ADDR1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpAddr1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_ADDR2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpAddr2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_ZIPCODE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpOwnZipcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_ADDR1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpOwnAddr1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_ADDR2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpOwnAddr2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_BIZ
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpBiz;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_ITEM
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpItem;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_IND_CD
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpIndCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_POST_ZIPCODE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpPostZipcode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_POST_ADDR1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpPostAddr1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_POST_ADDR2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpPostAddr2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_TEL1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpTel1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_TEL2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpTel2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_TEL3
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpTel3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_FAX1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpFax1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_FAX2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpFax2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_FAX3
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpFax3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpOwnMob1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpOwnMob2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB3
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpOwnMob3;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_EMAIL
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpEmail;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_URL
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.SITE_BANK_CD
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String siteBankCd;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.SITE_DEPOSIT_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String siteDepositNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.SITE_DEPOSIT_NAME
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String siteDepositName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.HOST_ID
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String hostId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CONT_COMMENTS
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String contComments;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_REG_YN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpRegYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_OLD_ID
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpOldId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_REG_GUBN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpRegGubn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_PACKAGE_YN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpPackageYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_STATUS
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.ECOMMERCE_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String ecommerceNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.ESCROW_YN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String escrowYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.SITE_REG_YN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String siteRegYn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.SITE_DESC
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String siteDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.MAKE_TYPE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String makeType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.ADMIN_REG_DT
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private Date adminRegDt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.ADMIN_COMP_ID
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String adminCompId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.PG_TYPE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String pgType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.HOST_NM
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String hostNm;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.MEM_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String memNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_TEL
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpTel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_FAX
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpFax;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String corpOwnMob;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column SKYPG.TBLAPPLY_REGIST.TEMP_FLG
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	private String tempFlg;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_REG_DT
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_REG_DT
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpRegDt() {
		return corpRegDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_REG_DT
	 * @param corpRegDt  the value for SKYPG.TBLAPPLY_REGIST.CORP_REG_DT
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpRegDt(String corpRegDt) {
		this.corpRegDt = corpRegDt == null ? null : corpRegDt.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CONT_ID
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CONT_ID
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public Short getContId() {
		return contId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CONT_ID
	 * @param contId  the value for SKYPG.TBLAPPLY_REGIST.CONT_ID
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setContId(Short contId) {
		this.contId = contId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_NAME
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_NAME
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpName() {
		return corpName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_NAME
	 * @param corpName  the value for SKYPG.TBLAPPLY_REGIST.CORP_NAME
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpName(String corpName) {
		this.corpName = corpName == null ? null : corpName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_SANG_HO
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_SANG_HO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpSangHo() {
		return corpSangHo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_SANG_HO
	 * @param corpSangHo  the value for SKYPG.TBLAPPLY_REGIST.CORP_SANG_HO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpSangHo(String corpSangHo) {
		this.corpSangHo = corpSangHo == null ? null : corpSangHo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_TAX_NO
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_TAX_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpTaxNo() {
		return corpTaxNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_TAX_NO
	 * @param corpTaxNo  the value for SKYPG.TBLAPPLY_REGIST.CORP_TAX_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpTaxNo(String corpTaxNo) {
		this.corpTaxNo = corpTaxNo == null ? null : corpTaxNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_NO
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpNo() {
		return corpNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_NO
	 * @param corpNo  the value for SKYPG.TBLAPPLY_REGIST.CORP_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpNo(String corpNo) {
		this.corpNo = corpNo == null ? null : corpNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_NAME
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_OWN_NAME
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpOwnName() {
		return corpOwnName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_NAME
	 * @param corpOwnName  the value for SKYPG.TBLAPPLY_REGIST.CORP_OWN_NAME
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpOwnName(String corpOwnName) {
		this.corpOwnName = corpOwnName == null ? null : corpOwnName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_NO
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_OWN_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpOwnNo() {
		return corpOwnNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_NO
	 * @param corpOwnNo  the value for SKYPG.TBLAPPLY_REGIST.CORP_OWN_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpOwnNo(String corpOwnNo) {
		this.corpOwnNo = corpOwnNo == null ? null : corpOwnNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_ZIPCODE
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_ZIPCODE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpZipcode() {
		return corpZipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_ZIPCODE
	 * @param corpZipcode  the value for SKYPG.TBLAPPLY_REGIST.CORP_ZIPCODE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpZipcode(String corpZipcode) {
		this.corpZipcode = corpZipcode == null ? null : corpZipcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_ADDR1
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_ADDR1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpAddr1() {
		return corpAddr1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_ADDR1
	 * @param corpAddr1  the value for SKYPG.TBLAPPLY_REGIST.CORP_ADDR1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpAddr1(String corpAddr1) {
		this.corpAddr1 = corpAddr1 == null ? null : corpAddr1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_ADDR2
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_ADDR2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpAddr2() {
		return corpAddr2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_ADDR2
	 * @param corpAddr2  the value for SKYPG.TBLAPPLY_REGIST.CORP_ADDR2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpAddr2(String corpAddr2) {
		this.corpAddr2 = corpAddr2 == null ? null : corpAddr2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_ZIPCODE
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_OWN_ZIPCODE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpOwnZipcode() {
		return corpOwnZipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_ZIPCODE
	 * @param corpOwnZipcode  the value for SKYPG.TBLAPPLY_REGIST.CORP_OWN_ZIPCODE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpOwnZipcode(String corpOwnZipcode) {
		this.corpOwnZipcode = corpOwnZipcode == null ? null : corpOwnZipcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_ADDR1
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_OWN_ADDR1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpOwnAddr1() {
		return corpOwnAddr1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_ADDR1
	 * @param corpOwnAddr1  the value for SKYPG.TBLAPPLY_REGIST.CORP_OWN_ADDR1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpOwnAddr1(String corpOwnAddr1) {
		this.corpOwnAddr1 = corpOwnAddr1 == null ? null : corpOwnAddr1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_ADDR2
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_OWN_ADDR2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpOwnAddr2() {
		return corpOwnAddr2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_ADDR2
	 * @param corpOwnAddr2  the value for SKYPG.TBLAPPLY_REGIST.CORP_OWN_ADDR2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpOwnAddr2(String corpOwnAddr2) {
		this.corpOwnAddr2 = corpOwnAddr2 == null ? null : corpOwnAddr2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_BIZ
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_BIZ
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpBiz() {
		return corpBiz;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_BIZ
	 * @param corpBiz  the value for SKYPG.TBLAPPLY_REGIST.CORP_BIZ
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpBiz(String corpBiz) {
		this.corpBiz = corpBiz == null ? null : corpBiz.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_ITEM
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_ITEM
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpItem() {
		return corpItem;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_ITEM
	 * @param corpItem  the value for SKYPG.TBLAPPLY_REGIST.CORP_ITEM
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpItem(String corpItem) {
		this.corpItem = corpItem == null ? null : corpItem.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_IND_CD
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_IND_CD
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpIndCd() {
		return corpIndCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_IND_CD
	 * @param corpIndCd  the value for SKYPG.TBLAPPLY_REGIST.CORP_IND_CD
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpIndCd(String corpIndCd) {
		this.corpIndCd = corpIndCd == null ? null : corpIndCd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_POST_ZIPCODE
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_POST_ZIPCODE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpPostZipcode() {
		return corpPostZipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_POST_ZIPCODE
	 * @param corpPostZipcode  the value for SKYPG.TBLAPPLY_REGIST.CORP_POST_ZIPCODE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpPostZipcode(String corpPostZipcode) {
		this.corpPostZipcode = corpPostZipcode == null ? null : corpPostZipcode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_POST_ADDR1
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_POST_ADDR1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpPostAddr1() {
		return corpPostAddr1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_POST_ADDR1
	 * @param corpPostAddr1  the value for SKYPG.TBLAPPLY_REGIST.CORP_POST_ADDR1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpPostAddr1(String corpPostAddr1) {
		this.corpPostAddr1 = corpPostAddr1 == null ? null : corpPostAddr1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_POST_ADDR2
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_POST_ADDR2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpPostAddr2() {
		return corpPostAddr2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_POST_ADDR2
	 * @param corpPostAddr2  the value for SKYPG.TBLAPPLY_REGIST.CORP_POST_ADDR2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpPostAddr2(String corpPostAddr2) {
		this.corpPostAddr2 = corpPostAddr2 == null ? null : corpPostAddr2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_TEL1
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_TEL1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpTel1() {
		return corpTel1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_TEL1
	 * @param corpTel1  the value for SKYPG.TBLAPPLY_REGIST.CORP_TEL1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpTel1(String corpTel1) {
		this.corpTel1 = corpTel1 == null ? null : corpTel1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_TEL2
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_TEL2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpTel2() {
		return corpTel2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_TEL2
	 * @param corpTel2  the value for SKYPG.TBLAPPLY_REGIST.CORP_TEL2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpTel2(String corpTel2) {
		this.corpTel2 = corpTel2 == null ? null : corpTel2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_TEL3
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_TEL3
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpTel3() {
		return corpTel3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_TEL3
	 * @param corpTel3  the value for SKYPG.TBLAPPLY_REGIST.CORP_TEL3
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpTel3(String corpTel3) {
		this.corpTel3 = corpTel3 == null ? null : corpTel3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_FAX1
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_FAX1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpFax1() {
		return corpFax1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_FAX1
	 * @param corpFax1  the value for SKYPG.TBLAPPLY_REGIST.CORP_FAX1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpFax1(String corpFax1) {
		this.corpFax1 = corpFax1 == null ? null : corpFax1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_FAX2
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_FAX2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpFax2() {
		return corpFax2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_FAX2
	 * @param corpFax2  the value for SKYPG.TBLAPPLY_REGIST.CORP_FAX2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpFax2(String corpFax2) {
		this.corpFax2 = corpFax2 == null ? null : corpFax2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_FAX3
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_FAX3
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpFax3() {
		return corpFax3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_FAX3
	 * @param corpFax3  the value for SKYPG.TBLAPPLY_REGIST.CORP_FAX3
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpFax3(String corpFax3) {
		this.corpFax3 = corpFax3 == null ? null : corpFax3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB1
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpOwnMob1() {
		return corpOwnMob1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB1
	 * @param corpOwnMob1  the value for SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB1
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpOwnMob1(String corpOwnMob1) {
		this.corpOwnMob1 = corpOwnMob1 == null ? null : corpOwnMob1.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB2
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpOwnMob2() {
		return corpOwnMob2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB2
	 * @param corpOwnMob2  the value for SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB2
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpOwnMob2(String corpOwnMob2) {
		this.corpOwnMob2 = corpOwnMob2 == null ? null : corpOwnMob2.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB3
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB3
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpOwnMob3() {
		return corpOwnMob3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB3
	 * @param corpOwnMob3  the value for SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB3
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpOwnMob3(String corpOwnMob3) {
		this.corpOwnMob3 = corpOwnMob3 == null ? null : corpOwnMob3.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_EMAIL
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_EMAIL
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpEmail() {
		return corpEmail;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_EMAIL
	 * @param corpEmail  the value for SKYPG.TBLAPPLY_REGIST.CORP_EMAIL
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpEmail(String corpEmail) {
		this.corpEmail = corpEmail == null ? null : corpEmail.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_URL
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_URL
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpUrl() {
		return corpUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_URL
	 * @param corpUrl  the value for SKYPG.TBLAPPLY_REGIST.CORP_URL
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpUrl(String corpUrl) {
		this.corpUrl = corpUrl == null ? null : corpUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.SITE_BANK_CD
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.SITE_BANK_CD
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getSiteBankCd() {
		return siteBankCd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.SITE_BANK_CD
	 * @param siteBankCd  the value for SKYPG.TBLAPPLY_REGIST.SITE_BANK_CD
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setSiteBankCd(String siteBankCd) {
		this.siteBankCd = siteBankCd == null ? null : siteBankCd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.SITE_DEPOSIT_NO
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.SITE_DEPOSIT_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getSiteDepositNo() {
		return siteDepositNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.SITE_DEPOSIT_NO
	 * @param siteDepositNo  the value for SKYPG.TBLAPPLY_REGIST.SITE_DEPOSIT_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setSiteDepositNo(String siteDepositNo) {
		this.siteDepositNo = siteDepositNo == null ? null : siteDepositNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.SITE_DEPOSIT_NAME
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.SITE_DEPOSIT_NAME
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getSiteDepositName() {
		return siteDepositName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.SITE_DEPOSIT_NAME
	 * @param siteDepositName  the value for SKYPG.TBLAPPLY_REGIST.SITE_DEPOSIT_NAME
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setSiteDepositName(String siteDepositName) {
		this.siteDepositName = siteDepositName == null ? null : siteDepositName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.HOST_ID
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.HOST_ID
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getHostId() {
		return hostId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.HOST_ID
	 * @param hostId  the value for SKYPG.TBLAPPLY_REGIST.HOST_ID
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setHostId(String hostId) {
		this.hostId = hostId == null ? null : hostId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CONT_COMMENTS
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CONT_COMMENTS
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getContComments() {
		return contComments;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CONT_COMMENTS
	 * @param contComments  the value for SKYPG.TBLAPPLY_REGIST.CONT_COMMENTS
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setContComments(String contComments) {
		this.contComments = contComments == null ? null : contComments.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_REG_YN
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_REG_YN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpRegYn() {
		return corpRegYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_REG_YN
	 * @param corpRegYn  the value for SKYPG.TBLAPPLY_REGIST.CORP_REG_YN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpRegYn(String corpRegYn) {
		this.corpRegYn = corpRegYn == null ? null : corpRegYn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OLD_ID
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_OLD_ID
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpOldId() {
		return corpOldId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OLD_ID
	 * @param corpOldId  the value for SKYPG.TBLAPPLY_REGIST.CORP_OLD_ID
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpOldId(String corpOldId) {
		this.corpOldId = corpOldId == null ? null : corpOldId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_REG_GUBN
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_REG_GUBN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpRegGubn() {
		return corpRegGubn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_REG_GUBN
	 * @param corpRegGubn  the value for SKYPG.TBLAPPLY_REGIST.CORP_REG_GUBN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpRegGubn(String corpRegGubn) {
		this.corpRegGubn = corpRegGubn == null ? null : corpRegGubn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_PACKAGE_YN
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_PACKAGE_YN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpPackageYn() {
		return corpPackageYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_PACKAGE_YN
	 * @param corpPackageYn  the value for SKYPG.TBLAPPLY_REGIST.CORP_PACKAGE_YN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpPackageYn(String corpPackageYn) {
		this.corpPackageYn = corpPackageYn == null ? null : corpPackageYn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_STATUS
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_STATUS
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpStatus() {
		return corpStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_STATUS
	 * @param corpStatus  the value for SKYPG.TBLAPPLY_REGIST.CORP_STATUS
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpStatus(String corpStatus) {
		this.corpStatus = corpStatus == null ? null : corpStatus.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.ECOMMERCE_NO
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.ECOMMERCE_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getEcommerceNo() {
		return ecommerceNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.ECOMMERCE_NO
	 * @param ecommerceNo  the value for SKYPG.TBLAPPLY_REGIST.ECOMMERCE_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setEcommerceNo(String ecommerceNo) {
		this.ecommerceNo = ecommerceNo == null ? null : ecommerceNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.ESCROW_YN
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.ESCROW_YN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getEscrowYn() {
		return escrowYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.ESCROW_YN
	 * @param escrowYn  the value for SKYPG.TBLAPPLY_REGIST.ESCROW_YN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setEscrowYn(String escrowYn) {
		this.escrowYn = escrowYn == null ? null : escrowYn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.SITE_REG_YN
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.SITE_REG_YN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getSiteRegYn() {
		return siteRegYn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.SITE_REG_YN
	 * @param siteRegYn  the value for SKYPG.TBLAPPLY_REGIST.SITE_REG_YN
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setSiteRegYn(String siteRegYn) {
		this.siteRegYn = siteRegYn == null ? null : siteRegYn.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.SITE_DESC
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.SITE_DESC
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getSiteDesc() {
		return siteDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.SITE_DESC
	 * @param siteDesc  the value for SKYPG.TBLAPPLY_REGIST.SITE_DESC
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setSiteDesc(String siteDesc) {
		this.siteDesc = siteDesc == null ? null : siteDesc.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.MAKE_TYPE
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.MAKE_TYPE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getMakeType() {
		return makeType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.MAKE_TYPE
	 * @param makeType  the value for SKYPG.TBLAPPLY_REGIST.MAKE_TYPE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setMakeType(String makeType) {
		this.makeType = makeType == null ? null : makeType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.ADMIN_REG_DT
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.ADMIN_REG_DT
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public Date getAdminRegDt() {
		return adminRegDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.ADMIN_REG_DT
	 * @param adminRegDt  the value for SKYPG.TBLAPPLY_REGIST.ADMIN_REG_DT
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setAdminRegDt(Date adminRegDt) {
		this.adminRegDt = adminRegDt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.ADMIN_COMP_ID
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.ADMIN_COMP_ID
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getAdminCompId() {
		return adminCompId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.ADMIN_COMP_ID
	 * @param adminCompId  the value for SKYPG.TBLAPPLY_REGIST.ADMIN_COMP_ID
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setAdminCompId(String adminCompId) {
		this.adminCompId = adminCompId == null ? null : adminCompId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.PG_TYPE
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.PG_TYPE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getPgType() {
		return pgType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.PG_TYPE
	 * @param pgType  the value for SKYPG.TBLAPPLY_REGIST.PG_TYPE
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setPgType(String pgType) {
		this.pgType = pgType == null ? null : pgType.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.HOST_NM
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.HOST_NM
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getHostNm() {
		return hostNm;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.HOST_NM
	 * @param hostNm  the value for SKYPG.TBLAPPLY_REGIST.HOST_NM
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setHostNm(String hostNm) {
		this.hostNm = hostNm == null ? null : hostNm.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.MEM_NO
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.MEM_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getMemNo() {
		return memNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.MEM_NO
	 * @param memNo  the value for SKYPG.TBLAPPLY_REGIST.MEM_NO
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setMemNo(String memNo) {
		this.memNo = memNo == null ? null : memNo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_TEL
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_TEL
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpTel() {
		return corpTel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_TEL
	 * @param corpTel  the value for SKYPG.TBLAPPLY_REGIST.CORP_TEL
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpTel(String corpTel) {
		this.corpTel = corpTel == null ? null : corpTel.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_FAX
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_FAX
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpFax() {
		return corpFax;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_FAX
	 * @param corpFax  the value for SKYPG.TBLAPPLY_REGIST.CORP_FAX
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpFax(String corpFax) {
		this.corpFax = corpFax == null ? null : corpFax.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getCorpOwnMob() {
		return corpOwnMob;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB
	 * @param corpOwnMob  the value for SKYPG.TBLAPPLY_REGIST.CORP_OWN_MOB
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setCorpOwnMob(String corpOwnMob) {
		this.corpOwnMob = corpOwnMob == null ? null : corpOwnMob.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column SKYPG.TBLAPPLY_REGIST.TEMP_FLG
	 * @return  the value of SKYPG.TBLAPPLY_REGIST.TEMP_FLG
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public String getTempFlg() {
		return tempFlg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column SKYPG.TBLAPPLY_REGIST.TEMP_FLG
	 * @param tempFlg  the value for SKYPG.TBLAPPLY_REGIST.TEMP_FLG
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	public void setTempFlg(String tempFlg) {
		this.tempFlg = tempFlg == null ? null : tempFlg.trim();
	}
}