package com.dzpay.admin.model.skypg;

import java.util.Date;

public class TblofficeAdmin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_ID
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_GP_NO
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String adminGpNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_PWD
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String adminPwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_NM
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String adminNm;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.SUB_DEPT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String subDept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.JOB_TIT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String jobTit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.EMAIL
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.COMP_TEL
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String compTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.MOB_TEL
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String mobTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.FAX_TEL
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String faxTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.USE_YN
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String useYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.REG_DT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private Date regDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.REG_ID
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String regId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.MOD_DT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private Date modDt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_TYPE
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String adminType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.SITE_CD
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String siteCd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.CORP_ID
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String corpId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.VIEW_TYPE
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String viewType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.SHOP_TYPE
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String shopType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.SITE_HOSTING_ID
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String siteHostingId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.CHURCH_YN
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String churchYn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.PHONE_NO
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String phoneNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SKYPG.TBLOFFICE_ADMIN.ENC_SALT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    private String encSalt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_ID
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.ADMIN_ID
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_ID
     *
     * @param adminId the value for SKYPG.TBLOFFICE_ADMIN.ADMIN_ID
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setAdminId(String adminId) {
        this.adminId = adminId == null ? null : adminId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_GP_NO
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.ADMIN_GP_NO
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getAdminGpNo() {
        return adminGpNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_GP_NO
     *
     * @param adminGpNo the value for SKYPG.TBLOFFICE_ADMIN.ADMIN_GP_NO
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setAdminGpNo(String adminGpNo) {
        this.adminGpNo = adminGpNo == null ? null : adminGpNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_PWD
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.ADMIN_PWD
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getAdminPwd() {
        return adminPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_PWD
     *
     * @param adminPwd the value for SKYPG.TBLOFFICE_ADMIN.ADMIN_PWD
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setAdminPwd(String adminPwd) {
        this.adminPwd = adminPwd == null ? null : adminPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_NM
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.ADMIN_NM
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getAdminNm() {
        return adminNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_NM
     *
     * @param adminNm the value for SKYPG.TBLOFFICE_ADMIN.ADMIN_NM
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setAdminNm(String adminNm) {
        this.adminNm = adminNm == null ? null : adminNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.SUB_DEPT
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.SUB_DEPT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getSubDept() {
        return subDept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.SUB_DEPT
     *
     * @param subDept the value for SKYPG.TBLOFFICE_ADMIN.SUB_DEPT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setSubDept(String subDept) {
        this.subDept = subDept == null ? null : subDept.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.JOB_TIT
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.JOB_TIT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getJobTit() {
        return jobTit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.JOB_TIT
     *
     * @param jobTit the value for SKYPG.TBLOFFICE_ADMIN.JOB_TIT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setJobTit(String jobTit) {
        this.jobTit = jobTit == null ? null : jobTit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.EMAIL
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.EMAIL
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.EMAIL
     *
     * @param email the value for SKYPG.TBLOFFICE_ADMIN.EMAIL
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.COMP_TEL
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.COMP_TEL
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getCompTel() {
        return compTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.COMP_TEL
     *
     * @param compTel the value for SKYPG.TBLOFFICE_ADMIN.COMP_TEL
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setCompTel(String compTel) {
        this.compTel = compTel == null ? null : compTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.MOB_TEL
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.MOB_TEL
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getMobTel() {
        return mobTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.MOB_TEL
     *
     * @param mobTel the value for SKYPG.TBLOFFICE_ADMIN.MOB_TEL
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setMobTel(String mobTel) {
        this.mobTel = mobTel == null ? null : mobTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.FAX_TEL
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.FAX_TEL
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getFaxTel() {
        return faxTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.FAX_TEL
     *
     * @param faxTel the value for SKYPG.TBLOFFICE_ADMIN.FAX_TEL
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setFaxTel(String faxTel) {
        this.faxTel = faxTel == null ? null : faxTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.USE_YN
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.USE_YN
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getUseYn() {
        return useYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.USE_YN
     *
     * @param useYn the value for SKYPG.TBLOFFICE_ADMIN.USE_YN
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setUseYn(String useYn) {
        this.useYn = useYn == null ? null : useYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.REG_DT
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.REG_DT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public Date getRegDt() {
        return regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.REG_DT
     *
     * @param regDt the value for SKYPG.TBLOFFICE_ADMIN.REG_DT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.REG_ID
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.REG_ID
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getRegId() {
        return regId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.REG_ID
     *
     * @param regId the value for SKYPG.TBLOFFICE_ADMIN.REG_ID
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setRegId(String regId) {
        this.regId = regId == null ? null : regId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.MOD_DT
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.MOD_DT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public Date getModDt() {
        return modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.MOD_DT
     *
     * @param modDt the value for SKYPG.TBLOFFICE_ADMIN.MOD_DT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_TYPE
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.ADMIN_TYPE
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getAdminType() {
        return adminType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.ADMIN_TYPE
     *
     * @param adminType the value for SKYPG.TBLOFFICE_ADMIN.ADMIN_TYPE
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setAdminType(String adminType) {
        this.adminType = adminType == null ? null : adminType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.SITE_CD
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.SITE_CD
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getSiteCd() {
        return siteCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.SITE_CD
     *
     * @param siteCd the value for SKYPG.TBLOFFICE_ADMIN.SITE_CD
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setSiteCd(String siteCd) {
        this.siteCd = siteCd == null ? null : siteCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.CORP_ID
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.CORP_ID
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getCorpId() {
        return corpId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.CORP_ID
     *
     * @param corpId the value for SKYPG.TBLOFFICE_ADMIN.CORP_ID
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setCorpId(String corpId) {
        this.corpId = corpId == null ? null : corpId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.VIEW_TYPE
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.VIEW_TYPE
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getViewType() {
        return viewType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.VIEW_TYPE
     *
     * @param viewType the value for SKYPG.TBLOFFICE_ADMIN.VIEW_TYPE
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setViewType(String viewType) {
        this.viewType = viewType == null ? null : viewType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.SHOP_TYPE
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.SHOP_TYPE
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getShopType() {
        return shopType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.SHOP_TYPE
     *
     * @param shopType the value for SKYPG.TBLOFFICE_ADMIN.SHOP_TYPE
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setShopType(String shopType) {
        this.shopType = shopType == null ? null : shopType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.SITE_HOSTING_ID
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.SITE_HOSTING_ID
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getSiteHostingId() {
        return siteHostingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.SITE_HOSTING_ID
     *
     * @param siteHostingId the value for SKYPG.TBLOFFICE_ADMIN.SITE_HOSTING_ID
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setSiteHostingId(String siteHostingId) {
        this.siteHostingId = siteHostingId == null ? null : siteHostingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.CHURCH_YN
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.CHURCH_YN
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getChurchYn() {
        return churchYn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.CHURCH_YN
     *
     * @param churchYn the value for SKYPG.TBLOFFICE_ADMIN.CHURCH_YN
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setChurchYn(String churchYn) {
        this.churchYn = churchYn == null ? null : churchYn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.PHONE_NO
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.PHONE_NO
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getPhoneNo() {
        return phoneNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.PHONE_NO
     *
     * @param phoneNo the value for SKYPG.TBLOFFICE_ADMIN.PHONE_NO
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo == null ? null : phoneNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SKYPG.TBLOFFICE_ADMIN.ENC_SALT
     *
     * @return the value of SKYPG.TBLOFFICE_ADMIN.ENC_SALT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public String getEncSalt() {
        return encSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SKYPG.TBLOFFICE_ADMIN.ENC_SALT
     *
     * @param encSalt the value for SKYPG.TBLOFFICE_ADMIN.ENC_SALT
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    public void setEncSalt(String encSalt) {
        this.encSalt = encSalt == null ? null : encSalt.trim();
    }
}