package com.dzpay.admin.mapper;

import com.dzpay.admin.model.skypg.TblapplyRegist;
import java.util.List;

public interface TblapplyRegistMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKYPG.TBLAPPLY_REGIST
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	int insert(TblapplyRegist record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table SKYPG.TBLAPPLY_REGIST
	 * @mbg.generated  Tue Aug 04 17:46:26 KST 2020
	 */
	List<TblapplyRegist> selectAll();

	// auto created 救登辑 流立 积己
    TblapplyRegist selectOne(String admin_comp_id);
}