package com.dzpay.admin.mapper;

import com.dzpay.admin.model.skypg.TblofficeAdmin;
import java.util.List;

public interface TblofficeAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKYPG.TBLOFFICE_ADMIN
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    int insert(TblofficeAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SKYPG.TBLOFFICE_ADMIN
     *
     * @mbg.generated Tue Aug 04 15:36:05 KST 2020
     */
    List<TblofficeAdmin> selectAll();
}